 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.*;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Hose.hosenGroesse;
import invoice.QuittungMaker;


/**
 *
 * Neue Bestellung aufnehmen, oder Bestellung ändern
 */
public class BestellungNeuAendern extends javax.swing.JDialog {
    private DefaultListModel<Artikel> listModel = new DefaultListModel<>();
    private boolean ok;
//Bestellung
    private Kunde kunde;
    private Integer id;    
    private LocalDate datum;    
    private double rabatt;
    private double versandkosten;
    private double endsumme = 0;
    private boolean bezahlt;    
    private boolean versendet;
    private Waehrung waehrung;
//Artikelliste
    private List<Artikel> artikelList;
    
     
      
/**    neue Bestellung */
    public BestellungNeuAendern(java.awt.Frame parent, Kunde kunde, Waehrung waehrung) {
        super(parent);
        setModal(true);
        initComponents();
        setLocation(200, 100);
        setTitle("Neue Bestellung Erstellen");
        
        artikelJList.setModel(listModel);
        
        this.waehrung = waehrung;
        this.kunde = kunde;        
        this.artikelList = new ArrayList<>();
       
        kundeLb.setText(this.kunde.getId() + ". " + this.kunde.getName());
        waehrungLb.setText(waehrung.toString());
        waehrungLb1.setText(waehrung.toString());
        waehrungLb2.setText(waehrung.toString());
        endsummeLb.setText(String.format("%,.2f", endsumme));
    }
    
/**    Bestellung ändern */
    public BestellungNeuAendern(java.awt.Frame parent, Kunde kunde, Bestellung bestellung, List<Artikel> artikelList){
        super(parent);
        setModal(true);
        initComponents();
        setLocation(200, 100);
        
        artikelJList.setModel(listModel);       
               
        this.kunde = kunde;        
        kundeLb.setText(this.kunde.getId() + ". " + this.kunde.getName());        
        
        setTitle("Bestellung ändern");
        
// Felder mit gegebenen Daten ausfüllen       
        this.id = bestellung.getId();
        this.datum = bestellung.getDatum();
     
        this.rabatt = bestellung.getRabatt();
        this.versandkosten = bestellung.getVersandkosten();
        this.waehrung = bestellung.getWaehrung();
        this.endsumme = bestellung.getEndsumme();            
        this.bezahltCb.setSelected(bestellung.isBezahlt());        
       
        this.versendetCb.setSelected(bestellung.isVersendet());
        this.endsummeLb.setText(String.valueOf(bestellung.getEndsumme()));
        waehrungLb.setText(waehrung.toString());
        waehrungLb1.setText(waehrung.toString());
        waehrungLb2.setText(waehrung.toString());
        endsummeLb.setText(String.format("%,.2f", endsumme));       
        rabattLb.setText(String.format("%,.2f", rabatt));
        versandkostenLb.setText(String.format("%,.2f", versandkosten)); 
        try{        
            jDatePicker.getModel().setDate(datum.getYear(), datum.getMonthValue()-1, datum.getDayOfMonth());
        }catch(NullPointerException e){    
        }
        jDatePicker.getModel().setSelected(true);
//  Liste mit Artikelliste auffüllen
//        this.artikelList = artikelList;
        this.artikelList = bestellung.getArtikelListe();        
        for (Artikel t : artikelList){
            listModel.addElement(t);
        } 
        
        
    }
    
    public BestellungNeuAendern(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kundeLb = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bezahltCb = new javax.swing.JCheckBox();
        versendetCb = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        artikelBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        artikelJList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        aendernBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        endsummeLb = new javax.swing.JLabel();
        waehrungLb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        waehrungLb2 = new javax.swing.JLabel();
        versandkostenLb = new javax.swing.JLabel();
        rabattOk = new javax.swing.JButton();
        waehrungLb1 = new javax.swing.JLabel();
        versandkostenOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfVersandkosten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rabattLb = new javax.swing.JLabel();
        tfRabatt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDatePicker = new org.jdatepicker.JDatePicker();
        quittungBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kundeLb.setText("jLabel1");

        okBtn.setText("Auftrag speichern");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Abbrechen");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Bestellung");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bezahltCb.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bezahltCb.setText("Bezahlt");

        versendetCb.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        versendetCb.setText("Verschickt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bezahltCb, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versendetCb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bezahltCb)
                    .addComponent(versendetCb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artikel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        deleteBtn.setText("Löschen");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        artikelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hose lang", "Hose kurz", "Mütze", "Schal", "Stirnband" }));
        artikelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artikelBoxActionPerformed(evt);
            }
        });

        artikelJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(artikelJList);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/jeans.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        aendernBtn.setText("Ändern");
        aendernBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aendernBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(artikelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(aendernBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artikelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aendernBtn)
                    .addComponent(deleteBtn))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Kunde:");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Gesamt:");

        endsummeLb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        endsummeLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        endsummeLb.setText("0");

        waehrungLb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        waehrungLb.setText("jLabel2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        waehrungLb2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        waehrungLb2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        waehrungLb2.setText("jLabel2");

        versandkostenLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versandkostenLb.setText("0");

        rabattOk.setText("Ok");
        rabattOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabattOkActionPerformed(evt);
            }
        });

        waehrungLb1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        waehrungLb1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        waehrungLb1.setText("jLabel2");

        versandkostenOk.setText("Ok");
        versandkostenOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versandkostenOkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Rabatt:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Versandkosten:");

        rabattLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rabattLb.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rabattLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(versandkostenLb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waehrungLb1)
                            .addComponent(waehrungLb2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfVersandkosten, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(versandkostenOk))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfRabatt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rabattOk)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(waehrungLb2)
                    .addComponent(rabattLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRabatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rabattOk))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(waehrungLb1)
                    .addComponent(versandkostenLb))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVersandkosten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versandkostenOk))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Datum:");

        jDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePickerActionPerformed(evt);
            }
        });

        quittungBtn.setText("Quittung erstellen");
        quittungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quittungBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(kundeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(quittungBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(okBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(cancelBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(endsummeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(waehrungLb))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kundeLb)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(jDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(endsummeLb)
                            .addComponent(waehrungLb))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn)
                    .addComponent(quittungBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.ok = true;       
        this.bezahlt = bezahltCb.isSelected();
        this.versendet = versendetCb.isSelected();
        dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void artikelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artikelBoxActionPerformed
        int selected = artikelBox.getSelectedIndex();
        Artikel artikel = null;
        String groesse = "";
        String anmerkung;
    
//        Artikelauswahl
        switch (selected){
            case 0:
                artikel = new HoseLang();
                break;
            case 1:
                artikel = new HoseKurz();
                break;
            case 2:
                artikel = new Muetze();
                break;
            case 3:
                artikel = new Schal();
                break;
            case 4:
                artikel = new Stirnband();
                break;            
        }
        
//        Größeneingabe
        if (selected == 2 || selected == 3 || selected == 4 ){
            groesse = (String)JOptionPane.showInputDialog(null, "Größenangaben:", 
            "Größe", JOptionPane.QUESTION_MESSAGE);
        } else{
            List<hosenGroesse> sizeList = Arrays.asList(hosenGroesse.values());
            Object[] options = new Object[sizeList.size()];
            for (int i = 0; i < options.length; i++){
                options[i] = sizeList.get(i).getMitZahlen();
            }
          
            String groesseInZahlen = (String)JOptionPane.showInputDialog(null, "Wähle die Größe aus!", 
            "Größe", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

//            groesse = hosenGroesse.zahlenAufBuchstabe(groesseInZahlen).toString();
            
            for (int i = 0; i < options.length; i++){
                if (options[i].equals(groesseInZahlen)){
                    groesse = sizeList.get(i).toString();
                }
            }       
        }

//        Anmerkung eingeben 
        if (groesse != null){
            try{  
                anmerkung = JOptionPane.showInputDialog(null, "Anmerkungen zum Artikel:", 
                        "Anmerkungen", JOptionPane.QUESTION_MESSAGE);

                artikel.setGroesse(groesse);                
                artikel.setWaehrung(waehrung);
                artikel.setAnmerkung(anmerkung);

                listModel.addElement(artikel);
                this.artikelList.add(artikel);

                endsumme += artikel.getPreis();
                endsummeLb.setText(String.format("%,.2f", endsumme));
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Falsche Eingabe!");
            }  
        }
    }//GEN-LAST:event_artikelBoxActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedIndex = artikelJList.getSelectedIndex();
        Artikel ausgewaehlt = artikelJList.getSelectedValue();
        if (selectedIndex != -1){
            endsumme -= ausgewaehlt.getPreis();
            endsummeLb.setText(String.format("%,.2f", endsumme));
            listModel.removeElement(ausgewaehlt);
            this.artikelList.remove(selectedIndex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.ok = false;
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void rabattOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabattOkActionPerformed
        try{
            endsumme += rabatt;
            NumberFormat format = NumberFormat.getInstance();
            Number number = format.parse(tfRabatt.getText());
            this.rabatt = number.doubleValue();
            
            rabattLb.setText(String.format(String.format("%,.2f", rabatt)));
            endsumme -= rabatt;
            endsummeLb.setText(String.format("%,.2f", endsumme));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Falsche Eingabe!");
        }  
    }//GEN-LAST:event_rabattOkActionPerformed

    private void versandkostenOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versandkostenOkActionPerformed
        try{
            endsumme -= versandkosten;
            NumberFormat format = NumberFormat.getInstance();
            Number number = format.parse(tfVersandkosten.getText());
            this.versandkosten = number.doubleValue();
            
            versandkostenLb.setText(String.format(String.format("%,.2f", versandkosten)));
            endsumme += versandkosten;
            endsummeLb.setText(String.format("%,.2f", endsumme));
        } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Falsche Eingabe!");
        }  
    }//GEN-LAST:event_versandkostenOkActionPerformed

    private void jDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePickerActionPerformed
        GregorianCalendar selectedDate = (GregorianCalendar) jDatePicker.getModel().getValue();
        LocalDate dateRead = LocalDateTime.ofInstant(selectedDate.toInstant(), selectedDate.getTimeZone().toZoneId()).toLocalDate();
        
        this.datum = dateRead;
    }//GEN-LAST:event_jDatePickerActionPerformed

    private void quittungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quittungBtnActionPerformed
        QuittungMaker invoiceFactory = new QuittungMaker(artikelList, waehrung, endsumme, kunde.getName());
        invoiceFactory.makePDF();
        JOptionPane.showMessageDialog(null, "Quittung erstellt");
    }//GEN-LAST:event_quittungBtnActionPerformed

    private void aendernBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aendernBtnActionPerformed
        int selectedIndex = artikelJList.getSelectedIndex();
        if (selectedIndex != -1){       
            Artikel ausgewaehlt = artikelJList.getSelectedValue();   

            try{                                         
                String anmerkung = (String) JOptionPane.showInputDialog(null, "Anmerkungen zum Artikel:", 
                        "Anmerkungen", JOptionPane.QUESTION_MESSAGE, null, null, ausgewaehlt.getAnmerkung());                          

                ausgewaehlt.setAnmerkung(anmerkung);
                listModel.remove(selectedIndex);
                this.artikelList.remove(selectedIndex);
                listModel.add(selectedIndex, ausgewaehlt);
                this.artikelList.add(selectedIndex, ausgewaehlt);            
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Falsche Eingabe!");
            }
        }        
    }//GEN-LAST:event_aendernBtnActionPerformed

    /** Wiedergabe eines Bestellung Objekts, wenn Fenster mit OK geschlossen*/
    public Optional<Bestellung> getBestellung(){
        if (this.ok){
            Bestellung bestellung = new Bestellung(id, kunde, datum, rabatt, 
                    versandkosten, endsumme, waehrung, bezahlt, versendet);            
            
            for (Artikel a : artikelList){
                a.setBestellung(bestellung);
            }
            
            bestellung.setArtikelListe(artikelList);
            
            return Optional.of(bestellung);
        }else{
            return Optional.empty();
        }
    }
    
    /** Wiedergabe einer Artikelliste, wenn Fenster mit OK geschlossen*/
    public Optional<List<Artikel>> getArtikelList(){
        if (this.ok){            
            return Optional.of(this.artikelList);
        }else{
            return Optional.empty();
        }
    }
    
    /** Wenn versendet, keine Änderungen mehr möglich */
    public void keineAenderungen(){
        bezahltCb.setEnabled(false);        
        artikelJList.setEnabled(false);
        deleteBtn.setEnabled(false);
        artikelBox.setEnabled(false);        
        rabattOk.setEnabled(false);
        versandkostenOk.setEnabled(false);        
        tfRabatt.setEnabled(false);
        tfVersandkosten.setEnabled(false);
        jDatePicker.setEnabled(false);        
    }    
    
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestellungNeuAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestellungNeuAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestellungNeuAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestellungNeuAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BestellungNeuAendern dialog = new BestellungNeuAendern(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aendernBtn;
    private javax.swing.JComboBox<String> artikelBox;
    private javax.swing.JList<model.Artikel> artikelJList;
    private javax.swing.JCheckBox bezahltCb;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel endsummeLb;
    private org.jdatepicker.JDatePicker jDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kundeLb;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton quittungBtn;
    private javax.swing.JLabel rabattLb;
    private javax.swing.JButton rabattOk;
    private javax.swing.JTextField tfRabatt;
    private javax.swing.JTextField tfVersandkosten;
    private javax.swing.JLabel versandkostenLb;
    private javax.swing.JButton versandkostenOk;
    private javax.swing.JCheckBox versendetCb;
    private javax.swing.JLabel waehrungLb;
    private javax.swing.JLabel waehrungLb1;
    private javax.swing.JLabel waehrungLb2;
    // End of variables declaration//GEN-END:variables

    
}
