/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.models.KundenTableModel;
import view.listeners.KundenListener;
import view.listeners.BestellungListener;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import model.Bestellung;
import model.Kunde;
import model.Waehrung;

/**
 *
 * Fenster für Kundendaten
 */
public class KundenPanel extends javax.swing.JPanel {
    private KundenListener kundenListener;
    private BestellungListener bestellungListener;
    private List<Kunde> kundenListe;    
    private KundenTableModel myTableModel;
    
    /**
     * Creates new form CustomerWindow
     */
    public KundenPanel(List<Kunde> customerList) {
        initComponents();
        setVisible(true);        
           
        myTableModel = (KundenTableModel) jTKunden.getModel();
        jTKunden.setAutoCreateRowSorter(true);
        reloadList(customerList);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        neuBtn = new javax.swing.JButton();
        aendernBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        neueBestBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTKunden = new javax.swing.JTable();

        setName(""); // NOI18N

        neuBtn.setText("Neu");
        neuBtn.setMaximumSize(new java.awt.Dimension(75, 32));
        neuBtn.setMinimumSize(new java.awt.Dimension(75, 32));
        neuBtn.setPreferredSize(new java.awt.Dimension(75, 32));
        neuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuBtnActionPerformed(evt);
            }
        });

        aendernBtn.setText("Ändern");
        aendernBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aendernBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Löschen");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        neueBestBtn.setText("Bestellung aufnehmen");
        neueBestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neueBestBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Kunden");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/user.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jTKunden.setModel(new view.models.KundenTableModel(kundenListe));
        jTKunden.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTKunden.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTKunden);
        TableColumnModel columnModel = jTKunden.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(25);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(180);
        columnModel.getColumn(3).setPreferredWidth(100);

        //TableRowSorter<TableModel> rendezo = new TableRowSorter<>(jTKunden.getModel());
        //jTVasarlo.setRowSorter(rendezo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(neueBestBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(neuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aendernBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(neuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aendernBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addGap(32, 32, 32)
                        .addComponent(neueBestBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void neuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuBtnActionPerformed
        KundeNeuAendern dialog = new KundeNeuAendern(new javax.swing.JFrame(), true);
        dialog.setVisible(true);        
        if (dialog.getKunde().isPresent()){
            Kunde kunde = dialog.getKunde().get();
            kundenListener.KundeWeitergegeben(kunde);
        }        
    }//GEN-LAST:event_neuBtnActionPerformed

    private void aendernBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aendernBtnActionPerformed
        int selectedRow = jTKunden.getSelectedRow();
        if (selectedRow != -1){
            int correctRow = jTKunden.convertRowIndexToModel(selectedRow);
            Kunde ausgewaehlt = myTableModel.getKundeAt(correctRow);        

            KundeNeuAendern dialog = new KundeNeuAendern(new javax.swing.JFrame(), 
                ausgewaehlt);
            dialog.setVisible(true); 
            Optional<Kunde> opti = dialog.getKunde();
            if (opti.isPresent()){
                Kunde kunde = opti.get();
                kundenListener.KundeWeitergegeben(kunde);
            }
        }
    }//GEN-LAST:event_aendernBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = jTKunden.getSelectedRow();
        if (selectedRow != -1){
            int correctRow = jTKunden.convertRowIndexToModel(selectedRow);
            Kunde ausgewaehlt = myTableModel.getKundeAt(correctRow);
            
            int input = JOptionPane.showConfirmDialog(null, "Kundendaten löschen?\nBestellungen werden auch gelöscht.", "Löschen",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (input == 0){            
                kundenListener.deleteSelected(ausgewaehlt.getId());
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void neueBestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neueBestBtnActionPerformed
        int selectedRow = jTKunden.getSelectedRow();
        if (selectedRow != -1){
            int rowInModel = jTKunden.convertRowIndexToModel(selectedRow);
            Kunde ausgewaehlt = myTableModel.getKundeAt(rowInModel);
            Waehrung[] options = {Waehrung.HUF, Waehrung.EUR};
            Waehrung waehrung = (Waehrung)JOptionPane.showInputDialog(null, "Währung auswählen!", 
                "Währung", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            
            if (waehrung != null){        
                BestellungNeuAendern dialog = new BestellungNeuAendern(new javax.swing.JFrame(), ausgewaehlt, waehrung);
                dialog.setVisible(true); 
                if (dialog.getBestellung().isPresent()){
                    Bestellung b = dialog.getBestellung().get();                    
                    bestellungListener.bestellungWeitergegeben(b);                    
                }                
            }
        }
    }//GEN-LAST:event_neueBestBtnActionPerformed

    public void setKundenListener(KundenListener listener){
        this.kundenListener = listener;
    }
    
    public void setBestellungListener(BestellungListener listener){
        this.bestellungListener = listener;
    }   

    
    /** Kunden aus der Liste anzeigen */
    public void reloadList(List<Kunde> list){
        this.kundenListe = list;
        myTableModel.setList(list);
        myTableModel.fireTableDataChanged();
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aendernBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTKunden;
    private javax.swing.JButton neuBtn;
    private javax.swing.JButton neueBestBtn;
    // End of variables declaration//GEN-END:variables
}
